name: Publish documentation

on:  
  workflow_dispatch:

jobs:
    publish-docs:
        runs-on: ubuntu-latest
        environment: prod

        steps:
        - name: Checkout the code
          uses: actions/checkout@v4
        
        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install mkdocs mkdocs-material mkdocs-material-extensions pymdown-extensions
        
        - name: Build the documentation
          run: |
            cd ./mkdocs
            mkdocs build --verbose --clean --strict
            ls -laR ./site

        - name: copy file via ssh key
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.MKDOCS_HOST }}
            username: ${{ secrets.MKDOCS_USERNAME }}
            port: ${{ secrets.MKDOCS_PORT }}            
            key: ${{ secrets.MKDOCS_KEY }}
            source: "./site/"
            target: ${{ secrets.MKDOCS_TARGET }}         